apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-catalog-api
  labels:
    app: catalog-api
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: catalog-api
  template:
    metadata:
      labels:
        app: catalog-api
    spec:
      containers:
        - name: catalog-api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: SERVICE_NAME
              value: "catalog-api"
            - name: PORT
              value: {{ .Values.env.PORT | quote }}
            - name: LOGGER_ENVIRONMENT
              value: {{ .Values.env.LOGGER_ENVIRONMENT | quote }}
            - name: LOGGER_LEVEL
              value: {{ .Values.env.LOGGER_LEVEL | quote }}
            - name: LOGGER_NAMESPACE
              value: {{ .Values.env.LOGGER_NAMESPACE | quote }}
            # Inject database URI from the config
            - name: URI
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-catalog-api-secret
                  key: database-uri
