# Server Configuration
server.port=${PORT:8090}

# MongoDB Configuration
spring.data.mongodb.uri=${URI:mongodb://localhost:27017}
spring.data.mongodb.database=catalog

# In Spring Boot, MongoDB authentication can be passed natively via the URI. 
# Or using specific properties:
spring.data.mongodb.username=${USER:admin}
spring.data.mongodb.password=${PASSWORD:admin}

# Swagger / OpenAPI Path
springdoc.swagger-ui.path=/swagger-ui.html

# Logger Settings mapping
logging.namespace=${LOGGER_NAMESPACE:}
logging.level.root=${LOGGER_LEVEL:INFO}
